### PR TITLE
Allow passing a recipe directly as a callable

### PR DESCRIPTION
**Pull request by saimn**
@kiloRomeoAlpha - This is the change I proposed some time ago, to allow passing directly a recipe function. What do you think about it ?

### CODE REVIEW

**Review by KathleenLabrie — COMMENTED** [review]
@chris-simpson, @saimn What to we think about this old pull request from Ken?

**Comment by chris-simpson** [comment]
Isn't it a PR from Simon? So presumably Simon likes it. I've never had cause to use the `Reduce()` API (I've only come across it in `autoredux` when sorting out the SExtractor memory issues) so I can't comment except saying it looks OK and it seems like it adds useful functionality.

**Comment by KathleenLabrie** [comment]
Yes!  Sorry.   I only saw the bold kiloRomeoAlpha it was addressed to.

If we all agree then, let's do it.

**Comment by saimn** [comment]
I also forgot about this PR ;). I guess I can merge it then.

**Pull request merged**
