### PR TITLE
Simplify setup and declare dependencies

### PR DESCRIPTION
**Pull request by saimn**

### CODE REVIEW

**Comment by KathleenLabrie** [comment]
Following up on this.   A few things to note.   We've already discussed the accidental inclusion of .pyc files, which would be a problem for sdist, for example.  So, if we could remove them from the PACKAGE_DATA list created with the "*" then that would great.

The other issue I have is with find_packages looking at ".".   This will grab everything, including stuff we don't want package.  While not ideal, I can foresee a case where we have a package in development that we want to exclude from the packaging for the time being.   It could be removed explicitly I guess, but wouldn't it be better to run find_packages on "astrodata", "gemini_instruments", "geminidr", "gempy", and "recipe_system", making it explicit that those are the packages we want to release and install in site-packages?   BTW, I haven't checked carefully, this new setup.py will have the imports be "import astrodata", not "from dragons import astrodata", right?

Finally, you have already noted on slack that "geminidr/gemini/lookup/spectrophotometric_standards" need to be added to the PACKAGE_DATA.

**Comment by saimn** [comment]
> The other issue I have is with find_packages looking at ".". This will grab everything, including stuff we don't want package. While not ideal, I can foresee a case where we have a package in development that we want to exclude from the packaging for the time being. It could be removed explicitly I guess, but wouldn't it be better to run find_packages on "astrodata", "gemini_instruments", "geminidr", "gempy", and "recipe_system", making it explicit that those are the packages we want to release and install in site-packages? 

The problem doing that is that it gives a relative package name:
```
In [2]: find_packages('gempy', exclude=['*tests*'])
Out[2]: 
['library',
 'adlibrary',
 'eti_core',
 'gemini',
 'utils',
 'numdisplay',
 'display',
 'library.config',
 'gemini.eti']
```

Using `find_packages('.', exclude=['*tests*'])` is much simpler, and you could still use `exclude` if needed to exclude a package in development, or modify manually the list returned by `find_packages`.

> BTW, I haven't checked carefully, this new setup.py will have the imports be "import astrodata", not "from dragons import astrodata", right?

Yes sure, I did not change the package structure.

**Comment by saimn** [comment]
> Finally, you have already noted on slack that "geminidr/gemini/lookup/spectrophotometric_standards" need to be added to the PACKAGE_DATA.

Yes, I did that but found that `package_data` is a bit annoying to use for recursive includes (for `adcc/client`):
https://github.com/GeminiDRSoftware/DRAGONS/pull/92/commits/50a162dda233e02dd1f53d146adfdd7f98be3de6

Another solution is to use `MANIFEST.in`, much easier in this case. We had a `MANIFEST.in` file but it was not used (it is used only if `include_package_data=True` is in the setup). So in the latest commits I replaced `package_data` with `MANIFEST.in`, and added a `global-exclude` for .pyc and other temporary files. 

Looking at the diff with the sdist file generated on master:
```diff
dragons-3.0.0.dev0/
+dragons-3.0.0.dev0/LICENSE
 dragons-3.0.0.dev0/MANIFEST.in
 dragons-3.0.0.dev0/PKG-INFO
+dragons-3.0.0.dev0/README.md
 dragons-3.0.0.dev0/astrodata/
 dragons-3.0.0.dev0/astrodata/__init__.py
 dragons-3.0.0.dev0/astrodata/_version.py
@@ -16,6 +18,8 @@
 dragons-3.0.0.dev0/dragons.egg-info/PKG-INFO
 dragons-3.0.0.dev0/dragons.egg-info/SOURCES.txt
 dragons-3.0.0.dev0/dragons.egg-info/dependency_links.txt
+dragons-3.0.0.dev0/dragons.egg-info/not-zip-safe
+dragons-3.0.0.dev0/dragons.egg-info/requires.txt
 dragons-3.0.0.dev0/dragons.egg-info/top_level.txt
 dragons-3.0.0.dev0/gemini_instruments/
 dragons-3.0.0.dev0/gemini_instruments/__init__.py
@@ -132,6 +136,7 @@
 dragons-3.0.0.dev0/geminidr/f2/lookups/BPM/f2_image_illumination.fits
 dragons-3.0.0.dev0/geminidr/f2/lookups/FOV.py
 dragons-3.0.0.dev0/geminidr/f2/lookups/__init__.py
+dragons-3.0.0.dev0/geminidr/f2/lookups/lowresargon.dat
 dragons-3.0.0.dev0/geminidr/f2/lookups/maskdb.py
 dragons-3.0.0.dev0/geminidr/f2/parameters_f2.py
 dragons-3.0.0.dev0/geminidr/f2/parameters_f2_image.py
@@ -146,6 +151,11 @@
 dragons-3.0.0.dev0/geminidr/f2/recipes/qa/recipes_DARK.py
 dragons-3.0.0.dev0/geminidr/f2/recipes/qa/recipes_FLAT_IMAGE.py
 dragons-3.0.0.dev0/geminidr/f2/recipes/qa/recipes_IMAGE.py
+dragons-3.0.0.dev0/geminidr/f2/recipes/ql/
+dragons-3.0.0.dev0/geminidr/f2/recipes/ql/__init__.py
+dragons-3.0.0.dev0/geminidr/f2/recipes/ql/recipes_DARK.py
+dragons-3.0.0.dev0/geminidr/f2/recipes/ql/recipes_FLAT_IMAGE.py
+dragons-3.0.0.dev0/geminidr/f2/recipes/ql/recipes_IMAGE.py
 dragons-3.0.0.dev0/geminidr/f2/recipes/sq/
 dragons-3.0.0.dev0/geminidr/f2/recipes/sq/__init__.py
 dragons-3.0.0.dev0/geminidr/f2/recipes/sq/recipes_DARK.py
@@ -162,6 +172,11 @@
 dragons-3.0.0.dev0/geminidr/gemini/lookups/qa_constraints.py
 dragons-3.0.0.dev0/geminidr/gemini/lookups/source_detection/
 dragons-3.0.0.dev0/geminidr/gemini/lookups/source_detection/__init__.py
+dragons-3.0.0.dev0/geminidr/gemini/lookups/source_detection/default.conv
+dragons-3.0.0.dev0/geminidr/gemini/lookups/source_detection/default.nnw
+dragons-3.0.0.dev0/geminidr/gemini/lookups/source_detection/default.param
+dragons-3.0.0.dev0/geminidr/gemini/lookups/source_detection/default.sex
+dragons-3.0.0.dev0/geminidr/gemini/lookups/source_detection/default_nodq.param
 dragons-3.0.0.dev0/geminidr/gemini/lookups/source_detection/sextractor_dict.py
 dragons-3.0.0.dev0/geminidr/gemini/lookups/spectrophotometric_standards/
 dragons-3.0.0.dev0/geminidr/gemini/lookups/spectrophotometric_standards/bd+284211.dat
@@ -260,6 +275,8 @@
 dragons-3.0.0.dev0/geminidr/gmos/lookups/BPM/gmos-s_illum_HAM_11_12amp_v1.fits
 dragons-3.0.0.dev0/geminidr/gmos/lookups/BPM/gmos-s_illum_HAM_22_12amp_v1.fits
 dragons-3.0.0.dev0/geminidr/gmos/lookups/BPM/gmos-s_illum_HAM_44_12amp_v1.fits
+dragons-3.0.0.dev0/geminidr/gmos/lookups/CuAr_GMOS.dat
+dragons-3.0.0.dev0/geminidr/gmos/lookups/CuAr_GMOS_mixord.dat
 dragons-3.0.0.dev0/geminidr/gmos/lookups/MDF/
 dragons-3.0.0.dev0/geminidr/gmos/lookups/MDF/0.25arcsec.fits
 dragons-3.0.0.dev0/geminidr/gmos/lookups/MDF/0.5arcsec.fits
@@ -1573,3 +1590,4 @@
 dragons-3.0.0.dev0/recipe_system/utils/rs_utilities.py
 dragons-3.0.0.dev0/setup.cfg
 dragons-3.0.0.dev0/setup.py
+dragons-3.0.0.dev0/tox.ini
```
shows that on master:
- `geminidr/f2/recipes/ql/` is missing

**Comment by KathleenLabrie** [comment]
>  geminidr/f2/recipes/ql/
> geminidr/f2/lookups/lowresargon.dat and geminidr/gmos/lookups/CuAr_GMOS*.dat : Is it on purpose ?

I confirm that they need to be included.

Is there anything else that needs to be addressed before this can be merged in?

**Comment by saimn** [comment]
I rebased to fix the conflicts with master, so I think it's now good to go.
The diff on the sdist files between master and this branch now gives:
```
 dragons-3.1.0.dev0/
+dragons-3.1.0.dev0/LICENSE
 dragons-3.1.0.dev0/MANIFEST.in
 dragons-3.1.0.dev0/PKG-INFO
+dragons-3.1.0.dev0/README.md
 dragons-3.1.0.dev0/astrodata/
 dragons-3.1.0.dev0/astrodata/__init__.py
 dragons-3.1.0.dev0/astrodata/_version.py
@@ -16,6 +18,8 @@
 dragons-3.1.0.dev0/dragons.egg-info/PKG-INFO
 dragons-3.1.0.dev0/dragons.egg-info/SOURCES.txt
 dragons-3.1.0.dev0/dragons.egg-info/dependency_links.txt
+dragons-3.1.0.dev0/dragons.egg-info/not-zip-safe
+dragons-3.1.0.dev0/dragons.egg-info/requires.txt
 dragons-3.1.0.dev0/dragons.egg-info/top_level.txt
 dragons-3.1.0.dev0/gemini_instruments/
 dragons-3.1.0.dev0/gemini_instruments/__init__.py
@@ -1587,3 +1591,4 @@
 dragons-3.1.0.dev0/recipe_system/utils/rs_utilities.py
 dragons-3.1.0.dev0/setup.cfg
 dragons-3.1.0.dev0/setup.py
+dragons-3.1.0.dev0/tox.ini
```
which confirms that data files are correctly packaged, and a few additional files are included with this PR (license, readme, dependencies, and the tox file).

**Comment by KathleenLabrie** [comment]
If you are happy with it, go ahead with the merge.

**Comment by saimn** [comment]
Ok, merging then !

**Pull request merged**
