### PR TITLE
Use malloc/free to allocate tmp arrays in cyclip

### PR DESCRIPTION
**Pull request by saimn**
This is to avoid segfaults if using `iterclip` with an array with more than 10'000 elements. 
Also for the case of stacking a few images it will avoid allocating unnecessarily big arrays.

### CODE REVIEW

**Comment by chris-simpson** [comment]
That looks reasonable, from what I remember of C.

**Review by phirstgemini — COMMENTED** [review]
You really should to check the return value of malloc - it will return NULL if it's unable to allocate the memory. Sure, that shouldn't normally happen, but you'll get a segfault if it does and I'm sure you'll want to raise something rather than let that happen..

Sorry if I'm wrong and cython takes care of this for you, but it didn't last time I worked with it...

**Comment by saimn** [comment]
Yes, you're right. In the `def` function we can raise a `MemoryError`, I need to find the good way for the `cdef` function.

**Comment by phirstgemini** [comment]
I think you can just do
```
if not tmp:
  raise MemoryError()
```

immediately after the malloc line, no?

**Comment by saimn** [comment]
The first occurrence is in a `cdef` function, which cannot handle exceptions, so you define a return value that will be checked if an exception happen: https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values

**Comment by phirstgemini** [comment]
Ah yes - good catch, I'd forgotten about that!

**Pull request merged**
